[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "npm run build --workspace=packages/shared",
  "npm run build --workspace=apps/backend"
]

[start]
cmd = "npm start --workspace=apps/backend"
